"""Alert schemas for BitOK KYT API."""

from __future__ import annotations

from datetime import datetime

from pydantic import BaseModel, Field

from .common import PaginatedResponse
from .enums import AlertStatus, RiskLevel


class Alert(BaseModel):
    """Alert generated by the KYT system."""

    id: int = Field(..., description="Alert ID")
    status: AlertStatus = Field(..., description="Alert status")
    risk_level: RiskLevel = Field(..., description="Risk level that triggered alert")
    transfer_id: int | None = Field(
        default=None, description="Related transfer ID if applicable"
    )
    client_id: str | None = Field(default=None, description="Related client ID")
    description: str = Field(..., description="Alert description")
    created_at: datetime | None = Field(default=None, description="Creation timestamp")
    updated_at: datetime | None = Field(
        default=None, description="Last update timestamp"
    )
    resolved_at: datetime | None = Field(
        default=None, description="Resolution timestamp"
    )


# Type alias for paginated response
AlertListResponse = PaginatedResponse[Alert]
