// Code generated by hand to replace protoc output in constrained environments.
// source: mpc.proto

package mpc

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *HealthRequest) Reset()         { *x = HealthRequest{} }
func (x *HealthRequest) String() string { return protoimpl.X.MessageStringOf(x) }
func (*HealthRequest) ProtoMessage()    {}
func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type HealthResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Healthy        bool   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Version        string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	ActiveSessions int32  `protobuf:"varint,3,opt,name=active_sessions,json=activeSessions,proto3" json:"active_sessions,omitempty"`
	StoredKeysets  int32  `protobuf:"varint,4,opt,name=stored_keysets,json=storedKeysets,proto3" json:"stored_keysets,omitempty"`
}

func (x *HealthResponse) Reset()         { *x = HealthResponse{} }
func (x *HealthResponse) String() string { return protoimpl.X.MessageStringOf(x) }
func (*HealthResponse) ProtoMessage()    {}
func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mpc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type StartDKGRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionId    string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	WalletId     string `protobuf:"bytes,2,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	Threshold    int32  `protobuf:"varint,3,opt,name=threshold,proto3" json:"threshold,omitempty"`
	TotalParties int32  `protobuf:"varint,4,opt,name=total_parties,json=totalParties,proto3" json:"total_parties,omitempty"`
	PartyIndex   int32  `protobuf:"varint,5,opt,name=party_index,json=partyIndex,proto3" json:"party_index,omitempty"`
}

func (x *StartDKGRequest) Reset()         { *x = StartDKGRequest{} }
func (x *StartDKGRequest) String() string { return protoimpl.X.MessageStringOf(x) }
func (*StartDKGRequest) ProtoMessage()    {}
func (x *StartDKGRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mpc_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type StartDKGResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success   bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error     string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Round1Msg []byte `protobuf:"bytes,3,opt,name=round1_msg,json=round1Msg,proto3" json:"round1_msg,omitempty"`
}

func (x *StartDKGResponse) Reset()         { *x = StartDKGResponse{} }
func (x *StartDKGResponse) String() string { return protoimpl.X.MessageStringOf(x) }
func (*StartDKGResponse) ProtoMessage()    {}
func (x *StartDKGResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mpc_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type DKGRoundRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionId        string          `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Round            int32           `protobuf:"varint,2,opt,name=round,proto3" json:"round,omitempty"`
	IncomingMessages []*PartyMessage `protobuf:"bytes,3,rep,name=incoming_messages,json=incomingMessages,proto3" json:"incoming_messages,omitempty"`
}

func (x *DKGRoundRequest) Reset()         { *x = DKGRoundRequest{} }
func (x *DKGRoundRequest) String() string { return protoimpl.X.MessageStringOf(x) }
func (*DKGRoundRequest) ProtoMessage()    {}
func (x *DKGRoundRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mpc_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type PartyMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FromParty int32  `protobuf:"varint,1,opt,name=from_party,json=fromParty,proto3" json:"from_party,omitempty"`
	Payload   []byte `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *PartyMessage) Reset()         { *x = PartyMessage{} }
func (x *PartyMessage) String() string { return protoimpl.X.MessageStringOf(x) }
func (*PartyMessage) ProtoMessage()    {}
func (x *PartyMessage) ProtoReflect() protoreflect.Message {
	mi := &file_mpc_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type DKGRoundResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success     bool       `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error       string     `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	IsFinal     bool       `protobuf:"varint,3,opt,name=is_final,json=isFinal,proto3" json:"is_final,omitempty"`
	OutgoingMsg []byte     `protobuf:"bytes,4,opt,name=outgoing_msg,json=outgoingMsg,proto3" json:"outgoing_msg,omitempty"`
	Result      *DKGResult `protobuf:"bytes,5,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *DKGRoundResponse) Reset()         { *x = DKGRoundResponse{} }
func (x *DKGRoundResponse) String() string { return protoimpl.X.MessageStringOf(x) }
func (*DKGRoundResponse) ProtoMessage()    {}
func (x *DKGRoundResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mpc_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type DKGResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	KeysetId        string `protobuf:"bytes,1,opt,name=keyset_id,json=keysetId,proto3" json:"keyset_id,omitempty"`
	PublicKey       []byte `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	PublicKeyFull   []byte `protobuf:"bytes,3,opt,name=public_key_full,json=publicKeyFull,proto3" json:"public_key_full,omitempty"`
	EthereumAddress string `protobuf:"bytes,4,opt,name=ethereum_address,json=ethereumAddress,proto3" json:"ethereum_address,omitempty"`
}

func (x *DKGResult) Reset()         { *x = DKGResult{} }
func (x *DKGResult) String() string { return protoimpl.X.MessageStringOf(x) }
func (*DKGResult) ProtoMessage()    {}
func (x *DKGResult) ProtoReflect() protoreflect.Message {
	mi := &file_mpc_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type FinalizeDKGRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionId string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
}

func (x *FinalizeDKGRequest) Reset()         { *x = FinalizeDKGRequest{} }
func (x *FinalizeDKGRequest) String() string { return protoimpl.X.MessageStringOf(x) }
func (*FinalizeDKGRequest) ProtoMessage()    {}
func (x *FinalizeDKGRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mpc_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type FinalizeDKGResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool       `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error   string     `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Result  *DKGResult `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *FinalizeDKGResponse) Reset()         { *x = FinalizeDKGResponse{} }
func (x *FinalizeDKGResponse) String() string { return protoimpl.X.MessageStringOf(x) }
func (*FinalizeDKGResponse) ProtoMessage()    {}
func (x *FinalizeDKGResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mpc_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type SigningPermit struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TxRequestId          string `protobuf:"bytes,1,opt,name=tx_request_id,json=txRequestId,proto3" json:"tx_request_id,omitempty"`
	WalletId             string `protobuf:"bytes,2,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	KeysetId             string `protobuf:"bytes,3,opt,name=keyset_id,json=keysetId,proto3" json:"keyset_id,omitempty"`
	TxHash               []byte `protobuf:"bytes,4,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	ExpiresAt            int64  `protobuf:"varint,5,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	CoordinatorSignature []byte `protobuf:"bytes,6,opt,name=coordinator_signature,json=coordinatorSignature,proto3" json:"coordinator_signature,omitempty"`
}

func (x *SigningPermit) Reset()         { *x = SigningPermit{} }
func (x *SigningPermit) String() string { return protoimpl.X.MessageStringOf(x) }
func (*SigningPermit) ProtoMessage()    {}
func (x *SigningPermit) ProtoReflect() protoreflect.Message {
	mi := &file_mpc_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type StartSigningRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionId   string         `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	KeysetId    string         `protobuf:"bytes,2,opt,name=keyset_id,json=keysetId,proto3" json:"keyset_id,omitempty"`
	MessageHash []byte         `protobuf:"bytes,3,opt,name=message_hash,json=messageHash,proto3" json:"message_hash,omitempty"`
	Permit      *SigningPermit `protobuf:"bytes,4,opt,name=permit,proto3" json:"permit,omitempty"`
	PartyIndex  int32          `protobuf:"varint,5,opt,name=party_index,json=partyIndex,proto3" json:"party_index,omitempty"`
}

func (x *StartSigningRequest) Reset()         { *x = StartSigningRequest{} }
func (x *StartSigningRequest) String() string { return protoimpl.X.MessageStringOf(x) }
func (*StartSigningRequest) ProtoMessage()    {}
func (x *StartSigningRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mpc_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type StartSigningResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success   bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error     string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Round1Msg []byte `protobuf:"bytes,3,opt,name=round1_msg,json=round1Msg,proto3" json:"round1_msg,omitempty"`
}

func (x *StartSigningResponse) Reset()         { *x = StartSigningResponse{} }
func (x *StartSigningResponse) String() string { return protoimpl.X.MessageStringOf(x) }
func (*StartSigningResponse) ProtoMessage()    {}
func (x *StartSigningResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mpc_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type SigningRoundRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionId        string          `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Round            int32           `protobuf:"varint,2,opt,name=round,proto3" json:"round,omitempty"`
	IncomingMessages []*PartyMessage `protobuf:"bytes,3,rep,name=incoming_messages,json=incomingMessages,proto3" json:"incoming_messages,omitempty"`
}

func (x *SigningRoundRequest) Reset()         { *x = SigningRoundRequest{} }
func (x *SigningRoundRequest) String() string { return protoimpl.X.MessageStringOf(x) }
func (*SigningRoundRequest) ProtoMessage()    {}
func (x *SigningRoundRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mpc_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type SigningRoundResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success     bool           `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error       string         `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	IsFinal     bool           `protobuf:"varint,3,opt,name=is_final,json=isFinal,proto3" json:"is_final,omitempty"`
	OutgoingMsg []byte         `protobuf:"bytes,4,opt,name=outgoing_msg,json=outgoingMsg,proto3" json:"outgoing_msg,omitempty"`
	Result      *SigningResult `protobuf:"bytes,5,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *SigningRoundResponse) Reset()         { *x = SigningRoundResponse{} }
func (x *SigningRoundResponse) String() string { return protoimpl.X.MessageStringOf(x) }
func (*SigningRoundResponse) ProtoMessage()    {}
func (x *SigningRoundResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mpc_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type SigningResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SignatureR    []byte `protobuf:"bytes,1,opt,name=signature_r,json=signatureR,proto3" json:"signature_r,omitempty"`
	SignatureS    []byte `protobuf:"bytes,2,opt,name=signature_s,json=signatureS,proto3" json:"signature_s,omitempty"`
	SignatureV    int32  `protobuf:"varint,3,opt,name=signature_v,json=signatureV,proto3" json:"signature_v,omitempty"`
	FullSignature []byte `protobuf:"bytes,4,opt,name=full_signature,json=fullSignature,proto3" json:"full_signature,omitempty"`
}

func (x *SigningResult) Reset()         { *x = SigningResult{} }
func (x *SigningResult) String() string { return protoimpl.X.MessageStringOf(x) }
func (*SigningResult) ProtoMessage()    {}
func (x *SigningResult) ProtoReflect() protoreflect.Message {
	mi := &file_mpc_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type FinalizeSigningRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionId string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
}

func (x *FinalizeSigningRequest) Reset()         { *x = FinalizeSigningRequest{} }
func (x *FinalizeSigningRequest) String() string { return protoimpl.X.MessageStringOf(x) }
func (*FinalizeSigningRequest) ProtoMessage()    {}
func (x *FinalizeSigningRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mpc_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type FinalizeSigningResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool           `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error   string         `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Result  *SigningResult `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *FinalizeSigningResponse) Reset()         { *x = FinalizeSigningResponse{} }
func (x *FinalizeSigningResponse) String() string { return protoimpl.X.MessageStringOf(x) }
func (*FinalizeSigningResponse) ProtoMessage()    {}
func (x *FinalizeSigningResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mpc_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type GetKeysetInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	KeysetId string `protobuf:"bytes,1,opt,name=keyset_id,json=keysetId,proto3" json:"keyset_id,omitempty"`
}

func (x *GetKeysetInfoRequest) Reset()         { *x = GetKeysetInfoRequest{} }
func (x *GetKeysetInfoRequest) String() string { return protoimpl.X.MessageStringOf(x) }
func (*GetKeysetInfoRequest) ProtoMessage()    {}
func (x *GetKeysetInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mpc_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type GetKeysetInfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Exists          bool   `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	KeysetId        string `protobuf:"bytes,2,opt,name=keyset_id,json=keysetId,proto3" json:"keyset_id,omitempty"`
	WalletId        string `protobuf:"bytes,3,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	PublicKey       []byte `protobuf:"bytes,4,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	EthereumAddress string `protobuf:"bytes,5,opt,name=ethereum_address,json=ethereumAddress,proto3" json:"ethereum_address,omitempty"`
	CreatedAt       int64  `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	LastUsedAt      int64  `protobuf:"varint,7,opt,name=last_used_at,json=lastUsedAt,proto3" json:"last_used_at,omitempty"`
}

func (x *GetKeysetInfoResponse) Reset()         { *x = GetKeysetInfoResponse{} }
func (x *GetKeysetInfoResponse) String() string { return protoimpl.X.MessageStringOf(x) }
func (*GetKeysetInfoResponse) ProtoMessage()    {}
func (x *GetKeysetInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mpc_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type DeleteKeysetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	KeysetId string `protobuf:"bytes,1,opt,name=keyset_id,json=keysetId,proto3" json:"keyset_id,omitempty"`
	Reason   string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
}

func (x *DeleteKeysetRequest) Reset()         { *x = DeleteKeysetRequest{} }
func (x *DeleteKeysetRequest) String() string { return protoimpl.X.MessageStringOf(x) }
func (*DeleteKeysetRequest) ProtoMessage()    {}
func (x *DeleteKeysetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mpc_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type DeleteKeysetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error   string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *DeleteKeysetResponse) Reset()         { *x = DeleteKeysetResponse{} }
func (x *DeleteKeysetResponse) String() string { return protoimpl.X.MessageStringOf(x) }
func (*DeleteKeysetResponse) ProtoMessage()    {}
func (x *DeleteKeysetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mpc_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

var File_mpc_proto protoreflect.FileDescriptor

var file_mpc_proto_rawDesc = []byte(`syntax = "proto3";

package mpc;

option go_package = "github.com/collider/mpc-signer/proto";

service MPCSigner {
  rpc Health (HealthRequest) returns (HealthResponse);
  rpc StartDKG (StartDKGRequest) returns (StartDKGResponse);
  rpc DKGRound (DKGRoundRequest) returns (DKGRoundResponse);
  rpc FinalizeDKG (FinalizeDKGRequest) returns (FinalizeDKGResponse);
  rpc StartSigning (StartSigningRequest) returns (StartSigningResponse);
  rpc SigningRound (SigningRoundRequest) returns (SigningRoundResponse);
  rpc FinalizeSigning (FinalizeSigningRequest) returns (FinalizeSigningResponse);
  rpc GetKeysetInfo (GetKeysetInfoRequest) returns (GetKeysetInfoResponse);
  rpc DeleteKeyset (DeleteKeysetRequest) returns (DeleteKeysetResponse);
}

message HealthRequest {}

message HealthResponse {
  bool healthy = 1;
  string version = 2;
  int32 active_sessions = 3;
  int32 stored_keysets = 4;
}

message StartDKGRequest {
  string session_id = 1;
  string wallet_id = 2;
  int32 threshold = 3;
  int32 total_parties = 4;
  int32 party_index = 5;
}

message StartDKGResponse {
  bool success = 1;
  string error = 2;
  bytes round1_msg = 3;
}

message DKGRoundRequest {
  string session_id = 1;
  int32 round = 2;
  repeated PartyMessage incoming_messages = 3;
}

message PartyMessage {
  int32 from_party = 1;
  bytes payload = 2;
}

message DKGRoundResponse {
  bool success = 1;
  string error = 2;
  bool is_final = 3;
  bytes outgoing_msg = 4;
  DKGResult result = 5;
}

message DKGResult {
  string keyset_id = 1;
  bytes public_key = 2;
  bytes public_key_full = 3;
  string ethereum_address = 4;
}

message FinalizeDKGRequest {
  string session_id = 1;
}

message FinalizeDKGResponse {
  bool success = 1;
  string error = 2;
  DKGResult result = 3;
}

message SigningPermit {
  string tx_request_id = 1;
  string wallet_id = 2;
  string keyset_id = 3;
  bytes tx_hash = 4;
  int64 expires_at = 5;
  bytes coordinator_signature = 6;
}

message StartSigningRequest {
  string session_id = 1;
  string keyset_id = 2;
  bytes message_hash = 3;
  SigningPermit permit = 4;
  int32 party_index = 5;
}

message StartSigningResponse {
  bool success = 1;
  string error = 2;
  bytes round1_msg = 3;
}

message SigningRoundRequest {
  string session_id = 1;
  int32 round = 2;
  repeated PartyMessage incoming_messages = 3;
}

message SigningRoundResponse {
  bool success = 1;
  string error = 2;
  bool is_final = 3;
  bytes outgoing_msg = 4;
  SigningResult result = 5;
}

message SigningResult {
  bytes signature_r = 1;
  bytes signature_s = 2;
  int32 signature_v = 3;
  bytes full_signature = 4;
}

message FinalizeSigningRequest {
  string session_id = 1;
}

message FinalizeSigningResponse {
  bool success = 1;
  string error = 2;
  SigningResult result = 3;
}

message GetKeysetInfoRequest {
  string keyset_id = 1;
}

message GetKeysetInfoResponse {
  bool exists = 1;
  string keyset_id = 2;
  string wallet_id = 3;
  bytes public_key = 4;
  string ethereum_address = 5;
  int64 created_at = 6;
  int64 last_used_at = 7;
}

message DeleteKeysetRequest {
  string keyset_id = 1;
  string reason = 2;
}

message DeleteKeysetResponse {
  bool success = 1;
  string error = 2;
}
`)

var (
	file_mpc_proto_rawDescOnce sync.Once
	file_mpc_proto_rawDescData = file_mpc_proto_rawDesc
)

func file_mpc_proto_rawDescGZIP() []byte {
	file_mpc_proto_rawDescOnce.Do(func() {
		file_mpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_mpc_proto_rawDescData)
	})
	return file_mpc_proto_rawDescData
}

var file_mpc_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_mpc_proto_goTypes = []interface{}{
	(*HealthRequest)(nil),
	(*HealthResponse)(nil),
	(*StartDKGRequest)(nil),
	(*StartDKGResponse)(nil),
	(*DKGRoundRequest)(nil),
	(*PartyMessage)(nil),
	(*DKGRoundResponse)(nil),
	(*DKGResult)(nil),
	(*FinalizeDKGRequest)(nil),
	(*FinalizeDKGResponse)(nil),
	(*SigningPermit)(nil),
	(*StartSigningRequest)(nil),
	(*StartSigningResponse)(nil),
	(*SigningRoundRequest)(nil),
	(*SigningRoundResponse)(nil),
	(*SigningResult)(nil),
	(*FinalizeSigningRequest)(nil),
	(*FinalizeSigningResponse)(nil),
	(*GetKeysetInfoRequest)(nil),
	(*GetKeysetInfoResponse)(nil),
	(*DeleteKeysetRequest)(nil),
	(*DeleteKeysetResponse)(nil),
}
var file_mpc_proto_depIdxs = []int32{
	5,  // 0: mpc.DKGRoundRequest.incoming_messages:type_name -> mpc.PartyMessage
	7,  // 1: mpc.DKGRoundResponse.result:type_name -> mpc.DKGResult
	7,  // 2: mpc.FinalizeDKGResponse.result:type_name -> mpc.DKGResult
	10, // 3: mpc.StartSigningRequest.permit:type_name -> mpc.SigningPermit
	5,  // 4: mpc.SigningRoundRequest.incoming_messages:type_name -> mpc.PartyMessage
	15, // 5: mpc.SigningRoundResponse.result:type_name -> mpc.SigningResult
	15, // 6: mpc.FinalizeSigningResponse.result:type_name -> mpc.SigningResult
	2,  // 7: mpc.MPCSigner.StartDKG:input_type -> mpc.StartDKGRequest
	4,  // 8: mpc.MPCSigner.DKGRound:input_type -> mpc.DKGRoundRequest
	8,  // 9: mpc.MPCSigner.FinalizeDKG:input_type -> mpc.FinalizeDKGRequest
	11, // 10: mpc.MPCSigner.StartSigning:input_type -> mpc.StartSigningRequest
	13, // 11: mpc.MPCSigner.SigningRound:input_type -> mpc.SigningRoundRequest
	16, // 12: mpc.MPCSigner.FinalizeSigning:input_type -> mpc.FinalizeSigningRequest
	18, // 13: mpc.MPCSigner.GetKeysetInfo:input_type -> mpc.GetKeysetInfoRequest
	20, // 14: mpc.MPCSigner.DeleteKeyset:input_type -> mpc.DeleteKeysetRequest
	0,  // 15: mpc.MPCSigner.Health:input_type -> mpc.HealthRequest
	3,  // 16: mpc.MPCSigner.StartDKG:output_type -> mpc.StartDKGResponse
	6,  // 17: mpc.MPCSigner.DKGRound:output_type -> mpc.DKGRoundResponse
	9,  // 18: mpc.MPCSigner.FinalizeDKG:output_type -> mpc.FinalizeDKGResponse
	12, // 19: mpc.MPCSigner.StartSigning:output_type -> mpc.StartSigningResponse
	14, // 20: mpc.MPCSigner.SigningRound:output_type -> mpc.SigningRoundResponse
	17, // 21: mpc.MPCSigner.FinalizeSigning:output_type -> mpc.FinalizeSigningResponse
	19, // 22: mpc.MPCSigner.GetKeysetInfo:output_type -> mpc.GetKeysetInfoResponse
	21, // 23: mpc.MPCSigner.DeleteKeyset:output_type -> mpc.DeleteKeysetResponse
	1,  // 24: mpc.MPCSigner.Health:output_type -> mpc.HealthResponse
	16, // [16:25] is the sub-list for method output_type
	7,  // [7:16] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_mpc_proto_init() }
func file_mpc_proto_init() {
	if File_mpc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_mpc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HealthRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mpc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HealthResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mpc_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartDKGRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mpc_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartDKGResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mpc_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DKGRoundRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mpc_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PartyMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mpc_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DKGRoundResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mpc_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DKGResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mpc_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FinalizeDKGRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mpc_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FinalizeDKGResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mpc_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SigningPermit); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mpc_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartSigningRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mpc_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartSigningResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mpc_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SigningRoundRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mpc_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SigningRoundResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mpc_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SigningResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mpc_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FinalizeSigningRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mpc_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FinalizeSigningResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mpc_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetKeysetInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mpc_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetKeysetInfoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mpc_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteKeysetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mpc_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteKeysetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}

	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mpc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mpc_proto_goTypes,
		DependencyIndexes: file_mpc_proto_depIdxs,
		MessageInfos:      file_mpc_proto_msgTypes,
	}.Build()
	File_mpc_proto = out.File
	file_mpc_proto_rawDesc = nil
	file_mpc_proto_goTypes = nil
	file_mpc_proto_depIdxs = nil
}
