// Code generated by hand to replace protoc output in constrained environments.
// source: mpc.proto

package mpc

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

const _ = grpc.SupportPackageIsVersion7

type MPCSignerClient interface {
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
	StartDKG(ctx context.Context, in *StartDKGRequest, opts ...grpc.CallOption) (*StartDKGResponse, error)
	DKGRound(ctx context.Context, in *DKGRoundRequest, opts ...grpc.CallOption) (*DKGRoundResponse, error)
	FinalizeDKG(ctx context.Context, in *FinalizeDKGRequest, opts ...grpc.CallOption) (*FinalizeDKGResponse, error)
	StartSigning(ctx context.Context, in *StartSigningRequest, opts ...grpc.CallOption) (*StartSigningResponse, error)
	SigningRound(ctx context.Context, in *SigningRoundRequest, opts ...grpc.CallOption) (*SigningRoundResponse, error)
	FinalizeSigning(ctx context.Context, in *FinalizeSigningRequest, opts ...grpc.CallOption) (*FinalizeSigningResponse, error)
	GetKeysetInfo(ctx context.Context, in *GetKeysetInfoRequest, opts ...grpc.CallOption) (*GetKeysetInfoResponse, error)
	DeleteKeyset(ctx context.Context, in *DeleteKeysetRequest, opts ...grpc.CallOption) (*DeleteKeysetResponse, error)
}

type mpcSignerClient struct {
	cc grpc.ClientConnInterface
}

func NewMPCSignerClient(cc grpc.ClientConnInterface) MPCSignerClient {
	return &mpcSignerClient{cc}
}

func (c *mpcSignerClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, "/mpc.MPCSigner/Health", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mpcSignerClient) StartDKG(ctx context.Context, in *StartDKGRequest, opts ...grpc.CallOption) (*StartDKGResponse, error) {
	out := new(StartDKGResponse)
	err := c.cc.Invoke(ctx, "/mpc.MPCSigner/StartDKG", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mpcSignerClient) DKGRound(ctx context.Context, in *DKGRoundRequest, opts ...grpc.CallOption) (*DKGRoundResponse, error) {
	out := new(DKGRoundResponse)
	err := c.cc.Invoke(ctx, "/mpc.MPCSigner/DKGRound", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mpcSignerClient) FinalizeDKG(ctx context.Context, in *FinalizeDKGRequest, opts ...grpc.CallOption) (*FinalizeDKGResponse, error) {
	out := new(FinalizeDKGResponse)
	err := c.cc.Invoke(ctx, "/mpc.MPCSigner/FinalizeDKG", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mpcSignerClient) StartSigning(ctx context.Context, in *StartSigningRequest, opts ...grpc.CallOption) (*StartSigningResponse, error) {
	out := new(StartSigningResponse)
	err := c.cc.Invoke(ctx, "/mpc.MPCSigner/StartSigning", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mpcSignerClient) SigningRound(ctx context.Context, in *SigningRoundRequest, opts ...grpc.CallOption) (*SigningRoundResponse, error) {
	out := new(SigningRoundResponse)
	err := c.cc.Invoke(ctx, "/mpc.MPCSigner/SigningRound", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mpcSignerClient) FinalizeSigning(ctx context.Context, in *FinalizeSigningRequest, opts ...grpc.CallOption) (*FinalizeSigningResponse, error) {
	out := new(FinalizeSigningResponse)
	err := c.cc.Invoke(ctx, "/mpc.MPCSigner/FinalizeSigning", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mpcSignerClient) GetKeysetInfo(ctx context.Context, in *GetKeysetInfoRequest, opts ...grpc.CallOption) (*GetKeysetInfoResponse, error) {
	out := new(GetKeysetInfoResponse)
	err := c.cc.Invoke(ctx, "/mpc.MPCSigner/GetKeysetInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mpcSignerClient) DeleteKeyset(ctx context.Context, in *DeleteKeysetRequest, opts ...grpc.CallOption) (*DeleteKeysetResponse, error) {
	out := new(DeleteKeysetResponse)
	err := c.cc.Invoke(ctx, "/mpc.MPCSigner/DeleteKeyset", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

type MPCSignerServer interface {
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	StartDKG(context.Context, *StartDKGRequest) (*StartDKGResponse, error)
	DKGRound(context.Context, *DKGRoundRequest) (*DKGRoundResponse, error)
	FinalizeDKG(context.Context, *FinalizeDKGRequest) (*FinalizeDKGResponse, error)
	StartSigning(context.Context, *StartSigningRequest) (*StartSigningResponse, error)
	SigningRound(context.Context, *SigningRoundRequest) (*SigningRoundResponse, error)
	FinalizeSigning(context.Context, *FinalizeSigningRequest) (*FinalizeSigningResponse, error)
	GetKeysetInfo(context.Context, *GetKeysetInfoRequest) (*GetKeysetInfoResponse, error)
	DeleteKeyset(context.Context, *DeleteKeysetRequest) (*DeleteKeysetResponse, error)
}

type UnimplementedMPCSignerServer struct{}

func (UnimplementedMPCSignerServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedMPCSignerServer) StartDKG(context.Context, *StartDKGRequest) (*StartDKGResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartDKG not implemented")
}
func (UnimplementedMPCSignerServer) DKGRound(context.Context, *DKGRoundRequest) (*DKGRoundResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DKGRound not implemented")
}
func (UnimplementedMPCSignerServer) FinalizeDKG(context.Context, *FinalizeDKGRequest) (*FinalizeDKGResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FinalizeDKG not implemented")
}
func (UnimplementedMPCSignerServer) StartSigning(context.Context, *StartSigningRequest) (*StartSigningResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartSigning not implemented")
}
func (UnimplementedMPCSignerServer) SigningRound(context.Context, *SigningRoundRequest) (*SigningRoundResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SigningRound not implemented")
}
func (UnimplementedMPCSignerServer) FinalizeSigning(context.Context, *FinalizeSigningRequest) (*FinalizeSigningResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FinalizeSigning not implemented")
}
func (UnimplementedMPCSignerServer) GetKeysetInfo(context.Context, *GetKeysetInfoRequest) (*GetKeysetInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetKeysetInfo not implemented")
}
func (UnimplementedMPCSignerServer) DeleteKeyset(context.Context, *DeleteKeysetRequest) (*DeleteKeysetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteKeyset not implemented")
}

func RegisterMPCSignerServer(s grpc.ServiceRegistrar, srv MPCSignerServer) {
	s.RegisterService(&MPCSigner_ServiceDesc, srv)
}

func _MPCSigner_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MPCSignerServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mpc.MPCSigner/Health",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MPCSignerServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MPCSigner_StartDKG_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartDKGRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MPCSignerServer).StartDKG(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mpc.MPCSigner/StartDKG",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MPCSignerServer).StartDKG(ctx, req.(*StartDKGRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MPCSigner_DKGRound_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DKGRoundRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MPCSignerServer).DKGRound(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mpc.MPCSigner/DKGRound",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MPCSignerServer).DKGRound(ctx, req.(*DKGRoundRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MPCSigner_FinalizeDKG_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FinalizeDKGRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MPCSignerServer).FinalizeDKG(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mpc.MPCSigner/FinalizeDKG",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MPCSignerServer).FinalizeDKG(ctx, req.(*FinalizeDKGRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MPCSigner_StartSigning_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartSigningRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MPCSignerServer).StartSigning(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mpc.MPCSigner/StartSigning",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MPCSignerServer).StartSigning(ctx, req.(*StartSigningRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MPCSigner_SigningRound_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SigningRoundRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MPCSignerServer).SigningRound(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mpc.MPCSigner/SigningRound",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MPCSignerServer).SigningRound(ctx, req.(*SigningRoundRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MPCSigner_FinalizeSigning_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FinalizeSigningRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MPCSignerServer).FinalizeSigning(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mpc.MPCSigner/FinalizeSigning",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MPCSignerServer).FinalizeSigning(ctx, req.(*FinalizeSigningRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MPCSigner_GetKeysetInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetKeysetInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MPCSignerServer).GetKeysetInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mpc.MPCSigner/GetKeysetInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MPCSignerServer).GetKeysetInfo(ctx, req.(*GetKeysetInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MPCSigner_DeleteKeyset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteKeysetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MPCSignerServer).DeleteKeyset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mpc.MPCSigner/DeleteKeyset",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MPCSignerServer).DeleteKeyset(ctx, req.(*DeleteKeysetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var MPCSigner_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mpc.MPCSigner",
	HandlerType: (*MPCSignerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Health",
			Handler:    _MPCSigner_Health_Handler,
		},
		{
			MethodName: "StartDKG",
			Handler:    _MPCSigner_StartDKG_Handler,
		},
		{
			MethodName: "DKGRound",
			Handler:    _MPCSigner_DKGRound_Handler,
		},
		{
			MethodName: "FinalizeDKG",
			Handler:    _MPCSigner_FinalizeDKG_Handler,
		},
		{
			MethodName: "StartSigning",
			Handler:    _MPCSigner_StartSigning_Handler,
		},
		{
			MethodName: "SigningRound",
			Handler:    _MPCSigner_SigningRound_Handler,
		},
		{
			MethodName: "FinalizeSigning",
			Handler:    _MPCSigner_FinalizeSigning_Handler,
		},
		{
			MethodName: "GetKeysetInfo",
			Handler:    _MPCSigner_GetKeysetInfo_Handler,
		},
		{
			MethodName: "DeleteKeyset",
			Handler:    _MPCSigner_DeleteKeyset_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mpc.proto",
}
