# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from app.proto import mpc_pb2 as mpc__pb2


class MPCSignerStub(object):
    """MPCSigner service provides MPC operations for the bank signer node.
    This node holds the bank's share and participates in DKG and signing protocols.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Health = channel.unary_unary(
                '/mpc.MPCSigner/Health',
                request_serializer=mpc__pb2.HealthRequest.SerializeToString,
                response_deserializer=mpc__pb2.HealthResponse.FromString,
                )
        self.StartDKG = channel.unary_unary(
                '/mpc.MPCSigner/StartDKG',
                request_serializer=mpc__pb2.StartDKGRequest.SerializeToString,
                response_deserializer=mpc__pb2.StartDKGResponse.FromString,
                )
        self.DKGRound = channel.unary_unary(
                '/mpc.MPCSigner/DKGRound',
                request_serializer=mpc__pb2.DKGRoundRequest.SerializeToString,
                response_deserializer=mpc__pb2.DKGRoundResponse.FromString,
                )
        self.FinalizeDKG = channel.unary_unary(
                '/mpc.MPCSigner/FinalizeDKG',
                request_serializer=mpc__pb2.FinalizeDKGRequest.SerializeToString,
                response_deserializer=mpc__pb2.FinalizeDKGResponse.FromString,
                )
        self.StartSigning = channel.unary_unary(
                '/mpc.MPCSigner/StartSigning',
                request_serializer=mpc__pb2.StartSigningRequest.SerializeToString,
                response_deserializer=mpc__pb2.StartSigningResponse.FromString,
                )
        self.SigningRound = channel.unary_unary(
                '/mpc.MPCSigner/SigningRound',
                request_serializer=mpc__pb2.SigningRoundRequest.SerializeToString,
                response_deserializer=mpc__pb2.SigningRoundResponse.FromString,
                )
        self.FinalizeSigning = channel.unary_unary(
                '/mpc.MPCSigner/FinalizeSigning',
                request_serializer=mpc__pb2.FinalizeSigningRequest.SerializeToString,
                response_deserializer=mpc__pb2.FinalizeSigningResponse.FromString,
                )
        self.GetKeysetInfo = channel.unary_unary(
                '/mpc.MPCSigner/GetKeysetInfo',
                request_serializer=mpc__pb2.GetKeysetInfoRequest.SerializeToString,
                response_deserializer=mpc__pb2.GetKeysetInfoResponse.FromString,
                )
        self.DeleteKeyset = channel.unary_unary(
                '/mpc.MPCSigner/DeleteKeyset',
                request_serializer=mpc__pb2.DeleteKeysetRequest.SerializeToString,
                response_deserializer=mpc__pb2.DeleteKeysetResponse.FromString,
                )


class MPCSignerServicer(object):
    """MPCSigner service provides MPC operations for the bank signer node.
    This node holds the bank's share and participates in DKG and signing protocols.
    """

    def Health(self, request, context):
        """Health check
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartDKG(self, request, context):
        """==================== DKG ====================
        Start a new DKG session
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DKGRound(self, request, context):
        """Process a DKG protocol round
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FinalizeDKG(self, request, context):
        """Finalize DKG (optional, usually auto-finalizes)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartSigning(self, request, context):
        """==================== Signing ====================
        Start a new signing session
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SigningRound(self, request, context):
        """Process a signing protocol round
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FinalizeSigning(self, request, context):
        """Finalize signing (optional)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetKeysetInfo(self, request, context):
        """==================== Keyset Management ====================
        Get information about a stored keyset
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteKeyset(self, request, context):
        """Delete a keyset (for key rotation)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MPCSignerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=mpc__pb2.HealthRequest.FromString,
                    response_serializer=mpc__pb2.HealthResponse.SerializeToString,
            ),
            'StartDKG': grpc.unary_unary_rpc_method_handler(
                    servicer.StartDKG,
                    request_deserializer=mpc__pb2.StartDKGRequest.FromString,
                    response_serializer=mpc__pb2.StartDKGResponse.SerializeToString,
            ),
            'DKGRound': grpc.unary_unary_rpc_method_handler(
                    servicer.DKGRound,
                    request_deserializer=mpc__pb2.DKGRoundRequest.FromString,
                    response_serializer=mpc__pb2.DKGRoundResponse.SerializeToString,
            ),
            'FinalizeDKG': grpc.unary_unary_rpc_method_handler(
                    servicer.FinalizeDKG,
                    request_deserializer=mpc__pb2.FinalizeDKGRequest.FromString,
                    response_serializer=mpc__pb2.FinalizeDKGResponse.SerializeToString,
            ),
            'StartSigning': grpc.unary_unary_rpc_method_handler(
                    servicer.StartSigning,
                    request_deserializer=mpc__pb2.StartSigningRequest.FromString,
                    response_serializer=mpc__pb2.StartSigningResponse.SerializeToString,
            ),
            'SigningRound': grpc.unary_unary_rpc_method_handler(
                    servicer.SigningRound,
                    request_deserializer=mpc__pb2.SigningRoundRequest.FromString,
                    response_serializer=mpc__pb2.SigningRoundResponse.SerializeToString,
            ),
            'FinalizeSigning': grpc.unary_unary_rpc_method_handler(
                    servicer.FinalizeSigning,
                    request_deserializer=mpc__pb2.FinalizeSigningRequest.FromString,
                    response_serializer=mpc__pb2.FinalizeSigningResponse.SerializeToString,
            ),
            'GetKeysetInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetKeysetInfo,
                    request_deserializer=mpc__pb2.GetKeysetInfoRequest.FromString,
                    response_serializer=mpc__pb2.GetKeysetInfoResponse.SerializeToString,
            ),
            'DeleteKeyset': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteKeyset,
                    request_deserializer=mpc__pb2.DeleteKeysetRequest.FromString,
                    response_serializer=mpc__pb2.DeleteKeysetResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mpc.MPCSigner', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MPCSigner(object):
    """MPCSigner service provides MPC operations for the bank signer node.
    This node holds the bank's share and participates in DKG and signing protocols.
    """

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mpc.MPCSigner/Health',
            mpc__pb2.HealthRequest.SerializeToString,
            mpc__pb2.HealthResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StartDKG(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mpc.MPCSigner/StartDKG',
            mpc__pb2.StartDKGRequest.SerializeToString,
            mpc__pb2.StartDKGResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DKGRound(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mpc.MPCSigner/DKGRound',
            mpc__pb2.DKGRoundRequest.SerializeToString,
            mpc__pb2.DKGRoundResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def FinalizeDKG(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mpc.MPCSigner/FinalizeDKG',
            mpc__pb2.FinalizeDKGRequest.SerializeToString,
            mpc__pb2.FinalizeDKGResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StartSigning(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mpc.MPCSigner/StartSigning',
            mpc__pb2.StartSigningRequest.SerializeToString,
            mpc__pb2.StartSigningResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SigningRound(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mpc.MPCSigner/SigningRound',
            mpc__pb2.SigningRoundRequest.SerializeToString,
            mpc__pb2.SigningRoundResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def FinalizeSigning(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mpc.MPCSigner/FinalizeSigning',
            mpc__pb2.FinalizeSigningRequest.SerializeToString,
            mpc__pb2.FinalizeSigningResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetKeysetInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mpc.MPCSigner/GetKeysetInfo',
            mpc__pb2.GetKeysetInfoRequest.SerializeToString,
            mpc__pb2.GetKeysetInfoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteKeyset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mpc.MPCSigner/DeleteKeyset',
            mpc__pb2.DeleteKeysetRequest.SerializeToString,
            mpc__pb2.DeleteKeysetResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
